version: "3.5"

services:
  boilerplate_php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/boilerplate
      - ./docker/php.ini:/usr/local/etc/php/conf.d/app-php.ini
    working_dir: /var/www/boilerplate
    container_name: boilerplate_php
    networks:
      - back
      - db

  boilerplate_http:
    image: nginx:latest
    container_name: boilerplate_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/boilerplate
      - ./docker/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    environment:
      HTTP_API_HOST: $HTTP_API_HOST
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
      < /etc/nginx/conf.d/nginx.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    networks:
      - back

  boilerplate_db:
    image: mysql
    container_name: boilerplate_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate_uri
    volumes:
      - ./runtime/docker/db:/var/lib/mysql
    networks:
      - db

networks:
  db:
    driver: bridge
  back:
    driver: bridge